[window]
decorations = "none"
opacity = 1
padding.x = 10
padding.y = 10

[font]
normal = { family = "Ubuntu Mono Nerd Font", style = "Regular" }
size = 18.0

[scrolling]
history = 100000

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
