[window]
decorations = "none"
opacity = 1 

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 12.0

[scrolling]
history = 100000

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
