#! /bin/sh

# AUTORUN
pgrep -x sxhkd > /dev/null || sxhkd &
polybar left &
polybar center &
polybar right &
pgrep -x dunst > /dev/null || dunst &
sh "$HOME/.config/bspwm/wallpaper.sh"
picom &
sh -c "setxkbmap -option ''; setxkbmap -layout us,ru -option grp:caps_toggle" &
redshift -P -O 3800


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
