; =========================
; COLORS
; =========================
include-file=rose-pine-moon.ini

; =========================
; LEFT BAR
; =========================
[bar/left]
width = 31%
height = 22pt
offset-x = 1%
offset-y = 6

background = ${colors.background}
foreground = ${colors.foreground}

radius = 10
padding-left = 2
padding-right = 2
module-margin = 1

font-0 = "Iosevka Nerd Font:size=10;2"

modules-left = xworkspaces
modules-right = xwindow

line-size = 0
border-size = 0

enable-ipc = true

; =========================
; CENTER BAR
; =========================
[bar/center]
width = 10%
height = 22pt
offset-x = 45%
offset-y = 6

background = ${colors.background}
foreground = ${colors.foreground}

radius = 10

font-0 = "Iosevka Nerd Font:size=10;2"

modules-center = date

line-size = 0
border-size = 0

enable-ipc = true

; =========================
; RIGHT BAR
; =========================
[bar/right]
width = 31%
height = 22pt
offset-x = 67%
offset-y = 6

background = ${colors.background}
foreground = ${colors.foreground}

radius = 10
padding-left = 2
padding-right = 2
module-margin = 1

font-0 = "Iosevka Nerd Font:size=10;2"

modules-center = filesystem separator pulseaudio separator xkeyboard separator memory separator cpu separator wlan eth

line-size = 0
border-size = 0

enable-ipc = true

; =========================
; WORKSPACES
; =========================
[module/xworkspaces]
type = internal/xworkspaces

label-active = 
label-active-foreground = ${colors.primary}
label-active-padding = 1

label-occupied = 
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 1

label-empty = 
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

label-urgent = 
label-urgent-foreground = ${colors.alert}
label-urgent-padding = 1

; =========================
; WINDOW TITLE
; =========================
[module/xwindow]
type = internal/xwindow
label = %title:0:50:...%

; =========================
; FILESYSTEM
; =========================
[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
label-mounted =   %percentage_used%%
label-unmounted = not mounted
label-unmounted-foreground = ${colors.disabled}

; =========================
; AUDIO
; =========================
[module/pulseaudio]
type = internal/pulseaudio

format-volume =   <label-volume>
label-volume = %percentage%%

label-muted =  muted
label-muted-foreground = ${colors.disabled}

; =========================
; KEYBOARD
; =========================
[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout =   %layout%
label-layout-foreground = ${colors.primary}

; =========================
; MEMORY
; =========================
[module/memory]
type = internal/memory
interval = 2

format =   <label>
label = %percentage_used:2%%

; =========================
; CPU
; =========================
[module/cpu]
type = internal/cpu
interval = 2

format =   <label>
label = %percentage:2%%

; =========================
; NETWORK BASE
; =========================
[network-base]
type = internal/network
interval = 5

format-connected = <label-connected>
format-disconnected =  disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected =   %essid%

[module/eth]
inherit = network-base
interface-type = wired
label-connected =   %local_ip%

; =========================
; DATE
; =========================
[module/date]
type = internal/date
interval = 1

date =  %d.%m --  %H:%M
date-alt =  %d.%m.%Y

label = %date%
label-foreground = ${colors.primary}

[module/separator]
type = custom/text
content = " · "
content-foreground = ${colors.gray}

; =========================
; SETTINGS
; =========================
[settings]
screenchange-reload = true
pseudo-transparency = true

